version: "3"

services:
  discord:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
      - .env
    command: npx nodemon
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: myr14d
      MYSQL_DATABASE: myriad
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    logging:
      driver: none

volumes:
  data:
